### ISSUE TITLE
ValueError: math domain err

### ISSUE THREAD

**Issue by chhnb** [facebookresearch/RLCompOpt#2]
---

**Issue Description:**

When executing the `sh scripts/train_autophase_offline_q_value_rank.sh` script, I encounter the following error:

```
Error executing job with overrides: ['seed=2']
Traceback (most recent call last):
  File "rlcompopt/train.py", line 1210, in main
    main_real(args)
  File "rlcompopt/train.py", line 1497, in main_real
    last_loss, eval_loss = policy_gradient(
  File "rlcompopt/train.py", line 411, in policy_gradient
    eval_loss = policy_gradient(
  File "rlcompopt/train.py", line 386, in policy_gradient
    log.info(stats.summary(iters, multipliers=dict(loss=1000, lr=1000)))
  File "/home/cyh/miniconda3/envs/rlcompopt/lib/python3.8/site-packages/common_utils/multi_counter.py", line 122, in summary
    s += v.summary(info=info.ljust(self.max_key_len + 4), multiplier=multipliers.get(k, 1)) + "\n"
  File "/home/cyh/miniconda3/envs/rlcompopt/lib/python3.8/site-packages/common_utils/multi_counter.py", line 38, in summary
    std = math.sqrt(meanSqr - mean * mean + 1e-6)
ValueError: math domain error
```

**Steps to Reproduce:**

1. Execute the `sh scripts/train_autophase_offline_q_value_rank.sh` script.
2. Observe the error mentioned above.

**Expected Behavior:**

The script should execute without errors, allowing for the successful training of the autophase offline q-value rank model.

**Additional Information:**

- Environment: Miniconda3
- Python Version: 3.8
- Operating System: Ubuntu 18.04

Please let me know if further information is required to address this issue. Thank you.

---

Adjust the environment details and any other relevant information according to your setup. Let me know if you need any further assistance!

**Comment by youweiliang** [comment]
Hi, I checked the issue and found it was caused by the `meanSqr` and `mean` being very large numbers. If you change the line `std = math.sqrt(meanSqr - mean * mean + 1e-6)` to `std = numpy.sqrt(meanSqr - mean * mean + 1e-6)` (you need to import numpy to do that), it works fine.
